---
apiVersion: v1
kind: Pod
metadata:
  name: cm-s-pod
  labels:
    app: demo
spec:
  containers:
    - name: test
      image: alpine
      command:
        - sleep
        - 1d
      envFrom: 
        - configMapRef: 
            name: userinfo-cm
        - secretRef:
            name: userinfo-secret
