---
apiVersion: v1
kind: Pod
metadata:
  name: cm-s-pod-2
spec:
  containers:
    - name: test1
      image: alpine
      command:
        - sleep
        - 1d
      volumeMounts:
        - name: uservolume
          mountPath: /creds/username
        - name: passwordvolume
          mountPath: /creds/password
  volumes:
    - name: uservolume
      configMap:
        name: userinfo-cm
    - name: passwordvolume
      secret:
        secretName: userinfo-secret