---
apiVersion: v1
kind: Namespace
metadata:
  name: prod

---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: deploy-sample
  namespace: prod
  annotations:
    kubernetes.io/change-cause: "image updated to v2.0"
spec:
  minReadySeconds: 1
  replicas: 10
  selector:
    matchLabels:
      app: web
  strategy: 
    type: RollingUpdate
    rollingUpdate: 
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: web 
    spec:
      containers:
        - name: dsdeploy
          image: student338/deploy-sample:v2.0
          ports:
            - name: webport
              containerPort: 80
              protocol: TCP