---
apiVersion: v1
kind: Pod
metadata:
  name: nop2
  labels:
    app: nopdb
spec:
  containers:
    - name: nop-c
      image: mysql:8
      envFrom:
        - secretRef:
            name: db-cred
      