---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nop-deploy
spec:
  minReadySeconds: 5
  replicas: 3
  selector:
    matchLabels:
      app: nop
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxSurge: 50%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: nop
    spec: 
      containers:
        - name: nop
          image: shaikkhajaibrahim/nopcommerceaug23
          ports:
            - containerPort: 80
              protocol: TCP