---
apiVersion: v1
kind: Pod
metadata: 
  name: noppod
  labels:
    app: nopdb
spec:
  containers:
    - name: nopdb
      image: mysql:8
      envFrom:
        - secretRef:
            name: db-cred
    