---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc-lb
  labels:
    app: nginx
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - name: nginx-svc-port
      port: 80 
      targetPort: 80
      protocol: TCP
      